apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gssx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-gssx@sha256:8df2120f36829491449fa2383765ed9a8b1f7f290895e6f279bcc61b9c87bd12
        name: my-nodejs
        resources: {}
status: {}
